### ISSUE TITLE
Same issue with UI scale

### ISSUE THREAD

**Issue by ghost** [Sharlottes/UnitInfo#17]
even u give slider it does not work

**Comment by Sharlottes** [comment]
H have you tried to reset ui to press tap button on left side?

**Comment by CoalRock8642** [comment]
No. The letters are getting messed up. UI at 50% and yours UI scale to 250%.

**Comment by Sharlottes** [comment]
1. did you update mod?
2. where is screenshot?
3. Which device did you play on pc or mobile?
4. I have to make issue templates f

**Comment by Sharlottes** [comment]
closed bc no comment
