### ISSUE TITLE
Customizable keybinds for Pathfind overdrawing

### ISSUE THREAD

**Issue by LtMZ1** [Sharlottes/UnitInfo#22]
I use q for the schematic menu and every time i do shift + q the menu opens, so a custom keybind woud be very helpful.
I also woud like different colors for the path instead of different modes: orange (you decide the color) for ground units purple for leg and blue for naval.

Thx for the crash fix btw

**Comment by LtMZ1** [comment]
One to lock the target woud be very useful too

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/130385903-e3059982-9379-4f50-9caa-5d73f4f79d6f.png)

**Comment by Sharlottes** [comment]
~~i don't know how to make new KeyBind h~~
