### ISSUE TITLE
Ui improvements 

### ISSUE THREAD

**Issue by LtMZ1** [Sharlottes/UnitInfo#23]
I play with 75% ui scaling and 100% info ui scaling , setting it to 125% solves some of the issues and lowering it makes it worse. Still some elements exit their ui:

![name exits screen](https://user-images.githubusercontent.com/87947799/130147572-8bf2405c-9d3d-4055-820e-f035a77a3ec5.jpg)
![too small numbers](https://user-images.githubusercontent.com/87947799/130147574-ddb60d27-d137-47ac-9041-c4657cf9ab6f.jpg)
Maybe just for me, but the income one are too small, in 1.3 the size was already good enought.
![3 digit or more exits](https://user-images.githubusercontent.com/87947799/130147578-62bdc26d-3741-4719-b3b8-ebbf0abcc040.jpg)
If at 5 digits it exits it will be good enought

Also from 175% info ui and above you can't switch mode anymore because the unit ui covers the icons and at some point the hitboxes don't mach anymore

P.s. why did you even add 50% and 25%?
Maybe i'm just complaining for no reason bc phone users use them but for me they are waaay too small.

Maybe I look a bit too harsh but i want the best from a mod like this.

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/130341365-a03e5e0a-7081-4869-82c8-817eca864659.png)
![image](https://user-images.githubusercontent.com/60801210/130341369-f4f4ba45-6b0d-479e-8f23-1131e0663974.png)

>P.s. why did you even add 50% and 25%?
no idea. 

+
![image](https://user-images.githubusercontent.com/60801210/130341387-31055a1d-43c8-4477-bf0c-01f745ab9324.png)
max scaling is now 100%

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/130342357-57a2ce73-b9dc-400f-859a-bb3eb3eed236.png)

done yey
