### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by LH-bored** [Sharlottes/UnitInfo#24]
I can't click the button on the left of the screen. The coordinates of the button may be abnormal
![Screenshot_2021-08-23-17-12-13-98_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/89118268/130422101-ad217d3c-fd2c-45dd-94b6-a9fa30c8b929.jpg)

**Comment by LtMZ1** [comment]
![yep](https://user-images.githubusercontent.com/87947799/130454158-fdc6f020-31ca-47d0-b73a-da356820ec7d.jpg)
Yep it's offset

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/130563580-f800305d-68f5-409f-9003-587f1ccb36f2.png)
fixed

**Comment by LH-bored** [comment]
I think it may be because mod mistook the black box on the left side of the screen for a clickable screen. The black box is a feature of the mobile phone
![Uploading IMG_20210823_222317.jpg…]()

**Comment by LH-bored** [comment]
![Uploading IMG_20210823_222317.jpg…]()
I think it may be because mod mistook the black box on the left of the screen for a clickable screen. The black edge on the left is the feature of the mobile phone

**Comment by Sharlottes** [comment]
cannot see image
