### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by LtMZ1** [Sharlottes/UnitInfo#25]
Idk what it's going on but overtime the fps dropped from 60 (when i opened the save file)
To 23~ (it keeps dropping, now it's at 20 and i know it's this mod bc without it it stays still at 60) i now tested with the previus release and it works fine, so there has to be a recently added background process, that slowly decreases fps and increases memory usage.
I played on that save for around 20 minutes not doing anything significant

**Comment by LtMZ1** [comment]
My fps is dropping even if i never enable them

**Comment by LtMZ1** [comment]
Goes back to normal if i open the menu or if i am in the title screen, doesn't change if i change map or gamemode (editor)

**Comment by LtMZ1** [comment]
Increases memory too, now 600mb and 18fps

**Comment by Sharlottes** [comment]
most update() method are used for ui tap. so if it's laggy, you need to set Info UI Scaling.
~~i don't even know what did you open or see and the situation or map status.~~
