### ISSUE TITLE
Settings description outdated

### ISSUE THREAD

**Issue by LtMZ1** [Sharlottes/UnitInfo#26]
![update 1](https://user-images.githubusercontent.com/87947799/130455327-638a580e-d201-4ec8-9201-e19c22a6a4be.jpg)
![update 2](https://user-images.githubusercontent.com/87947799/130455334-523fc1a5-7cea-403a-86df-0444797f3851.jpg)

**Comment by LtMZ1** [comment]
Also change: "Change Bar Style" to a slider and put the credit in the description of the slider
![update 3](https://user-images.githubusercontent.com/87947799/130455704-4bd5cc82-b0f5-4e16-9fc7-803641faffe3.jpg)

**Comment by Sharlottes** [comment]
done
