### ISSUE TITLE
Ui position and performance bug

### ISSUE THREAD

**Issue by LighterTimes** [Sharlottes/UnitInfo#28]
I made sure to have downloaded the right release before submitting the issue.
![did you fix it](https://user-images.githubusercontent.com/87947799/130776124-8519d09e-d806-4139-b7c5-632aab33a303.jpg)
My mouse is on the message, but it thinks it's around where the ? is.

Win+shift+s doesn't capture the cursor, that's why there is a hand drawn mouse at his place

**Comment by parkuristt** [comment]
You can use Greenshot for screenshots including the cursor

**Comment by Sharlottes** [comment]
The problem is that's not on my pc h

**Comment by Sharlottes** [comment]
I cannot find the reason hhhhh

**Comment by LH-bored** [comment]
![IMG_20210828_183014](https://user-images.githubusercontent.com/89118268/131215110-e9ecfd39-37fc-4241-8b73-79507acd1e47.jpg)

**Comment by LH-bored** [comment]
This bug appears in version 1.3.3.2 and later

**Comment by Sharlottes** [comment]
goddammit what the fucking hell bug

**Comment by Sharlottes** [comment]
That table including player name, position is a tooltip, and it's constructed everytime when you try to move cursor on.

**Comment by Sharlottes** [comment]
The first problem is low fps without any pathline.
The second problem is the wrong position of tooltip.
The third problem is wtf tap button is not clickable?? @LH-bored

**Comment by Sharlottes** [comment]
~~just remove that tooltip and display its player name and pos. It would be much better and may solve low fps too~~

**Comment by LH-bored** [comment]
All I know is that there is a bug that can't be clicked, which happened on the mobile phone.
The other two you may want to ask @LtMZ1 .
@Sharlottes

**Comment by LH-bored** [comment]
All I know is that there is a bug that can't be clicked, which happened on the mobile phone.
The other two you may need to ask LtMZ1

**Comment by Sharlottes** [comment]
I want to die because i cannot find the reason

**Comment by LH-bored** [comment]
Maybe you can try moving the UI on the left to the top of the screen, or try rolling back the UI part to before 1.3.3.2?

**Comment by Sharlottes** [comment]
> Maybe you can try moving the UI on the left to the top of the screen, or try rolling back the UI part to before 1.3.3.2?

~~why don;t you just use ui scaling?~~

**Comment by LH-bored** [comment]
UI scaling does not solve the clickable problem :(
@Sharlottes

**Comment by Sharlottes** [comment]
> UI scaling does not solve the clickable problem :(
> @Sharlottes

did you update btw? It might be solved

**Comment by LH-bored** [comment]
> > UI scaling does not solve the clickable problem :(
> > @Sharlottes
> 
> did you update btw? It might be solved

I tried to update the version, but the MOD is still abnormal

**Comment by LH-bored** [comment]
I tried to update the version again, but the mod still has exceptions @Sharlottes

**Comment by LH-bored** [comment]
You can try marginTop(), marginLeft() to control the UI position
Of course, this may not be right

**Comment by Sharlottes** [comment]
i will make instant setting ui, which you can config some unitinfo settings on ingame screen.
this includes those pathline buttons, which lead us to solution.

**Comment by Sharlottes** [comment]
@Br0ad can you try it?
