### ISSUE TITLE
bloom errors on turret range preview

### ISSUE THREAD

**Issue by bloool** [Sharlottes/UnitInfo#31]
what it should look like normally
![image](https://user-images.githubusercontent.com/56099368/131177921-58bd3d6e-4cdb-452b-8dcd-a567cfb627a1.png)

then whenever a bullet appears it gets bloom until all bullets disappear
![image](https://user-images.githubusercontent.com/56099368/131177952-d71ac5c2-c19a-4f19-8e1d-55f26371f820.png)

this could probably be fixed by `Draw.reset()`

**Comment by MEEPofFaith** [comment]
bloom is related to layer, so normally it would always be glowing

**Comment by Sharlottes** [comment]
~~burn your gpu~~

**Comment by USMP-lancer** [comment]
i just think it looks funny

**Comment by USMP-lancer** [comment]
~~that bullet high tho~~

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/132114566-93481db8-6ee9-44cc-a6cf-a2d65ee2ee91.png)

doesn't happen. close issue
