### ISSUE TITLE
Crash on Foo Client

### ISSUE THREAD

**Issue by Erisfiregamer1** [Sharlottes/UnitInfo#40]
Crash:
ArcRuntime:
File not found: shaders/turretrange.frag

**Comment by Sharlottes** [comment]
I did some idiot things on releasing. I will fix it 6h later

**Comment by parkuristt** [comment]
The current release is broken, a new release would probably be made tomorrow

**Comment by Erisfiregamer1** [comment]
Ah, thanks for letting me know :D
also now that you have the dropdown for the blockinfo menu can you just add a setting to disable it fully

**Comment by Sharlottes** [comment]
I will add it on fixed version

**Comment by Erisfiregamer1** [comment]
YES! Thank you!
Us Foo Client users are happy about this :D

**Comment by Sharlottes** [comment]
![image](https://user-images.githubusercontent.com/60801210/133950690-606a9565-1018-4be9-a57b-74fe2a6e0509.png)
