### ISSUE TITLE
Foo Client incompatibilites

### ISSUE THREAD

**Issue by Erisfiregamer1** [Sharlottes/UnitInfo#41]
- Tile UI also closes power UI
- Lock onto unit feature starts Freecam

**Comment by Erisfiregamer1** [comment]
why do you ALWAYS break Foo Client

**Comment by Sharlottes** [comment]
* Use collapser button
* what

**Comment by Erisfiregamer1** [comment]
- Same problem, it collapses the power menu too
- There's a Freecam feature in foo client. clicking the lock on the left unit info menu starts it except the camera is just stuck.

**Comment by Sharlottes** [comment]
* use setting
![image](https://user-images.githubusercontent.com/60801210/133952750-9e93d10e-8a74-4226-9e20-5fb822cc3042.png)

* i will remove camera focusing

**Comment by Erisfiregamer1** [comment]
- setting STILL breaks it
- thank you

**Comment by Sharlottes** [comment]
* send screenshot

**Comment by Erisfiregamer1** [comment]
![Screenshot from 2021-09-20 15-22-41](https://user-images.githubusercontent.com/54373833/134061975-ceafed71-6bea-4b02-8a2f-2281c03f028a.png)

**Comment by Sharlottes** [comment]
buthed fixed this issue, will marged on v132
