### ISSUE TITLE
Crashes on pre-alpha 135

### ISSUE THREAD

**Issue by 228722** [Sharlottes/UnitInfo#54]
Version: pre-alpha build 135
OS: Linux xnull (aarch64)
Java Version: 0
Mods: unitinfo:1.5.3

> IllegalArgument: 'scaleX cannot be 0.'
Font$FontData.setScale: 943
Label.scaleAndComputePrefSize: 128
Label.getPrefWidth: 229
Cell.prefWidth: 118
Table.computeSize: 924
Table.getPrefWidth: 664
WidgetGroup.pack: 116
UnitDisplay$1.lambda$new$5: 80
-$$Lambda$UnitDisplay$1$xTd_W-02T0INF3SZxqia8fWbNOM.get: 2
Table.<init>: 75
UnitDisplay$1.lambda$new$6: 70
-$$Lambda$UnitDisplay$1$7_f7ubQTY3B0i4c-yWOXSCPGbO8.get: 2
Table.<init>: 75
UnitDisplay$1.<init>: 69
UnitDisplay.lambda$new$13$UnitDisplay: 56
-$$Lambda$UnitDisplay$NE3Chyiwe_9tycqyRlCT3-8ew3w.get: 4
Table.table: 275
Table.table: 269
UnitDisplay.lambda$new$17$UnitDisplay: 54
-$$Lambda$UnitDisplay$QvB5YpWduK2ZwSfaUD7O2PP4xRY.get: 4
Table.<init>: 70
UnitDisplay.<init>: 53
HudUi.lambda$addTable$62$HudUi: 319
-$$Lambda$HudUi$27PCwGQmSEB8L8NGNY0OrOHEtS8.get: 4
Table.<init>: 75
HudUi.addTable: 291
Main.lambda$init$1: 42
-$$Lambda$Main$iIse7P4CeXGB0w30ZHE0eqTs9qw.get: 2
ClientLauncher.lambda$update$11: 159
ClientLauncher.$r8$lambda$zpnJXmKKZVX7vjnDu3ow_Febh6g: 0
ClientLauncher$$ExternalSyntheticLambda0.get: 4
Events.lambda$fireWrap$3: 37
Events.$r8$lambda$2yxV4pnjxA1skQbmXK_eDcJ6tPY: 0
Events$$ExternalSyntheticLambda0.get: 4
Seq.each: 199
Events.fireWrap: 36
ClientLauncher.update: 157
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286

**Comment by Sharlottes** [comment]
did you update?

**Comment by 228722** [comment]
> did you try to update unitinfo mod?

There are 1.5.3 instead of 1.5.4. So, nothing changed 
![Screenshot_20220108-231308_File Manager +](https://user-images.githubusercontent.com/59439771/148658562-afbaa875-8465-464d-923e-b7be7da3113e.jpg)

**Comment by G-WE** [comment]
same mine crahes

**Comment by Sharlottes** [comment]
try this https://github.com/Sharlottes/UnitInfo/actions/runs/2095823996

**Comment by Sharlottes** [comment]
when i try latest action build on mobile, it's fixed
