### ISSUE TITLE
UI doesn't scale properly on mobile

### ISSUE THREAD

**Issue by abrasmag3** [Sharlottes/UnitInfo#7]
The  UI seems to break at any UI scale other than 50%. It also affects some vanilla text.  
![Screenshot_20210527-102736](https://user-images.githubusercontent.com/77550282/119855124-a8912100-bedf-11eb-9a22-72b4db33a668.png)  
100% UI scale (default)  
![Screenshot_20210527-113311](https://user-images.githubusercontent.com/77550282/119855208-b8106a00-bedf-11eb-8d16-ccdd311af09a.png)  
50% UI scale (problem fixed)

**Comment by MEEPofFaith** [comment]
# **< Paused >**

**Comment by Sharlottes** [comment]
OH SHIT

**Comment by Sharlottes** [comment]
fixed by removing scaling

**Comment by abrasmag3** [comment]
I have been reinstalling but it isn't fixed. Is it coming in another version?

**Comment by abrasmag3** [comment]
still not fixed, reopening

**Comment by Sharlottes** [comment]
i will check on tomorrow...hh

**Comment by Sharlottes** [comment]
fixed to push
